graphics:
  window_mode: windowed
  resolution:
    width: 1280
    height: 720
  shadow_quality: off
  vsync: false
  fps_limit: default60
  render_distance: medium
  show_grass: false
audio:
  ambient_enabled: true
  effects_enabled: true
